# Generated by Django 2.2.24 on 2021-06-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isenw_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
