# Generated by Django 2.2.24 on 2021-06-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isenw_app', '0002_auto_20210625_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='new',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
