# Generated by Django 2.2.24 on 2021-06-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isenw_app', '0003_content_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='new',
            field=models.FileField(default='isenw_app/uploads', upload_to=''),
        ),
    ]
