# Generated by Django 2.2.24 on 2021-06-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isenw_app', '0004_auto_20210625_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
    ]
