# Generated by Django 2.2.24 on 2021-06-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isenw_app', '0005_remove_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='new',
            field=models.FileField(upload_to='isenw_app/uploads'),
        ),
    ]
