# Generated by Django 2.2.24 on 2021-06-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isenw_app', '0006_auto_20210625_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='new',
        ),
    ]
