# Generated by Django 2.2.24 on 2021-06-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isenw_app', '0008_auto_20210625_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.AddField(
            model_name='content',
            name='Don',
            field=models.FileField(default='defau', upload_to='isenw_app/uploads', verbose_name='Key'),
        ),
    ]
