# Generated by Django 2.2.24 on 2021-06-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isenw_app', '0012_auto_20210625_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.FileField(default='', upload_to='isenw_app/uploads'),
        ),
    ]
