# Generated by Django 2.2.24 on 2021-06-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isenw_app', '0013_auto_20210625_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='bin_image',
            field=models.BinaryField(blank=True),
        ),
    ]
