# Generated by Django 2.2.24 on 2021-06-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isenw_app', '0014_content_bin_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='bin_image',
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(default='', upload_to='isenw_app/uploads'),
        ),
    ]
