# Generated by Django 2.2.24 on 2021-06-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isenw_app', '0016_auto_20210626_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(default='', max_length=500, upload_to='isenw_app/uploads'),
        ),
    ]
