# Generated by Django 2.2.24 on 2021-06-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isenw_app', '0018_remove_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(default='', max_length=500, upload_to='isenw_app/uploads'),
        ),
    ]
