# Generated by Django 3.1.3 on 2020-12-04 21:19

from django.db import migrations, models
import icml.storage


class Migration(migrations.Migration):

    dependencies = [
        ('icml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images')),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=icml.storage.OverwriteStorage(), upload_to='icml\\images'),
        ),
    ]
