# Generated by Django 3.1.3 on 2020-12-18 13:45

from django.db import migrations, models
import icml.storage


class Migration(migrations.Migration):

    dependencies = [
        ('icml', '0004_auto_20201205_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=icml.storage.OverwriteStorage(), upload_to='icml\\images'),
        ),
    ]
